number_tuplex = ("kavya", 25,"black","shitzu")
print(number_tuplex)
tuple_length = len(number_tuplex)
print("Length of the tuple:", tuple_length)
print(number_tuplex[0])
print(number_tuplex[0])
print(number_tuplex[1:3])
print(number_tuplex[-1])
print(number_tuplex[::-1])
